# Generated by Django 6.0.3 on 2026-03-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatparticipant_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='has_unread_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chats.message'),
        ),
    ]
